# Generated by Django 2.2.7 on 2020-01-06 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slicer', '0002_auto_20170310_0642'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imageseries',
            options={'verbose_name_plural': 'Image Series'},
        ),
        migrations.AddField(
            model_name='imageseries',
            name='png_file',
            field=models.ImageField(null=True, upload_to='png/'),
        ),
    ]
