# Generated by Django 2.2.7 on 2020-01-06 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slicer', '0003_auto_20200106_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageseries',
            name='png_file',
        ),
    ]
