# Generated by Django 2.2.7 on 2020-01-07 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slicer', '0005_imageseries_png_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageseries',
            name='png_files',
        ),
    ]
