# Generated by Django 2.2.7 on 2020-01-08 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slicer', '0006_remove_imageseries_png_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageseries',
            name='png_files',
            field=models.FileField(null=True, upload_to='png/'),
        ),
    ]
