# Generated by Django 2.2.7 on 2020-01-08 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slicer', '0008_auto_20200108_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageseries',
            name='png_files',
            field=models.TextField(null=True),
        ),
    ]
