# Generated by Django 2.2.7 on 2020-01-08 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slicer', '0009_auto_20200108_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageseries',
            name='png_files',
        ),
    ]
