# Generated by Django 2.2.7 on 2020-01-08 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slicer', '0010_remove_imageseries_png_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageseries',
            name='image_series_name',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
