# Generated by Django 2.2.7 on 2020-01-08 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slicer', '0011_imageseries_image_series_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageseries',
            name='image_series_name',
        ),
    ]
